version: '3.8'

services:
  backend_api:
    build:
      context: backend_api/
      dockerfile: docker/Dockerfile
    ports:
      - "${BACKEND_API_PORT:-8000}:8000"
    environment:
      - BACKEND_API_JWT_SECRET=${BACKEND_API_JWT_SECRET}
      - BACKEND_API_DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}
      - BACKEND_API_TASK_MANAGER_URL=http://task_manager_api:8000
    depends_on:
      - task_manager_api
  task_manager_api:
    build:
      context: task_manager_api/
      dockerfile: docker/Dockerfile
    environment:
      - TASK_MANAGER_PROVIDER_API_GATEWAY_URL=http://provider_api_gateway:8000
    ports:
      - "${TASK_MANAGER_API_GATEWAY_PORT:-8001}:8000"
    depends_on:
      - provider_api_gateway
  provider_api_gateway:
    build:
      context: provider_api_gateway/
      dockerfile: docker/Dockerfile
    ports:
      - "${PROVIDER_API_GATEWAY_PORT:-8002}:8000"
    environment:
      - REPLICATE_API_TOKEN=${REPLICATE_API_TOKEN}
  db:
    image: postgres:12
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
