version: '3.8'

services:
  backend_api:
    build:
      context: backend_api/
      dockerfile: docker/Dockerfile
    ports:
      - "${BACKEND_API_PORT:-8000}:8000"
    environment:
      - BACKEND_API_SECRET_KEY=${BACKEND_API_SECRET_KEY}
      - BACKEND_API_JWT_SECRET=${BACKEND_API_JWT_SECRET}
      - BACKEND_API_DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}
      - BACKEND_API_PROVIDER_API_URL=http://provider_api_gateway:8000
      - BACKEND_API_PROVIDER_NAME=replicate
      - BACKEND_API_ADMIN_USERNAME=${BACKEND_API_ADMIN_USERNAME}
      - BACKEND_API_ADMIN_PASSWORD=${BACKEND_API_ADMIN_PASSWORD}
  provider_api_gateway:
    build:
      context: provider_api_gateway/
      dockerfile: docker/Dockerfile
    expose:
      - 8000
    environment:
      - REPLICATE_API_TOKEN=${PROVIDER_REPLICATE_API_TOKEN}
  db:
    image: postgres:12
    expose:
      - 5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
