"""add icon

Revision ID: 227e5b308147
Revises: 6564756dc2e6
Create Date: 2024-08-04 14:21:25.250451

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlalchemy_file


# revision identifiers, used by Alembic.
revision = '227e5b308147'
down_revision = '6564756dc2e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('icon_svg', sqlalchemy_file.types.FileField(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'icon_svg')
    # ### end Alembic commands ###
