"""add balance popup model

Revision ID: 6564756dc2e6
Revises: e14cd248183c
Create Date: 2024-07-25 15:00:01.258314

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '6564756dc2e6'
down_revision = 'e14cd248183c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balance_popups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('price_usd', sa.Float(), nullable=False),
    sa.Column('address_to_pay', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('currency_to_pay', sa.Enum('ETH', 'USDT', name='currencytopayenum'), nullable=False),
    sa.Column('time_to_pay_minutes', sa.Integer(), nullable=False),
    sa.Column('pay_until', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('balance_popups')
    # ### end Alembic commands ###
