"""add datetime columns

Revision ID: c63fc4d52f09
Revises: f29c343d9e9f
Create Date: 2024-07-22 12:33:30.999545

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'c63fc4d52f09'
down_revision = 'f29c343d9e9f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('models', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('models', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('models', 'updated_at')
    op.drop_column('models', 'created_at')
    op.drop_column('categories', 'created_at')
    # ### end Alembic commands ###
