"""add transaction column to usage

Revision ID: f29c343d9e9f
Revises: 3b24d974316c
Create Date: 2024-07-22 12:05:59.134381

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'f29c343d9e9f'
down_revision = '3b24d974316c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usage', sa.Column('transaction_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'usage', 'transaction', ['transaction_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usage', type_='foreignkey')
    op.drop_column('usage', 'transaction_id')
    # ### end Alembic commands ###
